### ISSUE TITLE
Back button should restore query variables and scroll position

### ISSUE THREAD

**Issue by wincent** [wincent/masochist#11]
- [x] Scroll position.
- [ ] Query variables.

**Comment by wincent** [comment]
This is annoying enough to end users that I am going to call it a bug.

**Comment by trotzig** [comment]
Don't ask me how I came across this issue. But: @janpaul123 made a polyfill that we use @ Brigade. you might want to check it out: https://medium.com/brigade-engineering/maintaining-scroll-positions-in-all-browsers-a280d49bffca#.wjjk4hf2k

**Comment by wincent** [comment]
Thanks for the tip @trotzig. Any reason something like that couldn't be pushed upstream to https://github.com/rackt/scroll-behavior (which I'm using and which @janpaul123 mentions in the article). It already has three scroll behaviors; perhaps they'd be open to adding a fourth?

**Comment by wincent** [comment]
Scroll-handling got completely redone in https://github.com/wincent/masochist/commit/72b442c38502d426072ab1ff447b50b474b24549 so I am not sure if it's still an issue. Closing optimistically. Created https://github.com/wincent/masochist/issues/102 for the query variables side of things.
