### ISSUE TITLE
Update to Relay v12

### ISSUE THREAD

**Issue by wincent** [wincent/masochist#140]
... or to whatever is the latest at the time I get around to it: https://github.com/facebook/relay/releases

Principally so I can get rid of my persisted query hacks: https://github.com/facebook/relay/releases/tag/v2.0.0-rc.2

Disclaimer: it's possible I will never get to this. I have an experimental Relay-less rewrite about 3% completed in [the `next` branch](https://github.com/wincent/masochist/tree/next) at this time.

**Comment by jgcmarins** [comment]
Hello, @wincent.
Thanks for this awesome project and example on how to use Relay.

Any plans do bring Relay hooks (useQuery, useFragment and so on)?
They've been [released in experimental mode](https://github.com/facebook/relay/releases/tag/v6.0.0).

**Comment by wincent** [comment]
TBH, maybe not. I maintain this project just for fun, and working through a chain of breaking updates probably won't be much fun. I am occasionally spending time on the side on a from-scratch rewrite — because that *is* fun — but that may take a while (and may never be finished!).

**Comment by wincent** [comment]
Superseded by #180.
