### ISSUE TITLE
Double dot renders as an ellipsis (three periods) character on website

### ISSUE THREAD

**Issue by andyneff** [wincent/masochist#150]
When reading the git rules, I was confused as to why a "double dot" was a three period ellipsis character instead

https://github.com/wincent/masochist/blame/614e6c960fd8b114b1d60c550d663c354311aa5d/content/wiki/Legal%20Git%20branch%20names.md#L11 appears to be right, however something in between converts it to the … character instead on https://wincent.com/wiki/Legal_Git_branch_names

I'm not sure what is causing this, so I can't make a PR to fix it.

**Comment by wincent** [comment]
That'll be a quirk of the Markdown parsing. I think the fix will be to surround it in backticks instead of double quotes.

**Comment by wincent** [comment]
Yep, backtick-quoting seems [to have fixed it](https://wincent.com/wiki/Legal_Git_branch_names). Thanks for reporting @andyneff.
