### ISSUE TITLE
I cant find the documentation

### ISSUE THREAD

**Issue by 4theLoveofForms** [wincent/masochist#189]

**Comment by 4theLoveofForms** [comment]
in GitHub readme it says "See the Wikitext::Parser attributes documentation...".  I can't find that.  The link https://wincent.com/products/wikitext/doc has no information.

**Comment by wincent** [comment]
I think you're looking for: http://wincent.github.io/wikitext/

Where did you see the broken link, @4theLoveofForms? (if you can point me in the right direction, I can hopefully fix it)
