### ISSUE TITLE
Linkes to GitHub repo for `Command-T` is now broken on the site.

### ISSUE THREAD

**Issue by svaderia** [wincent/masochist#225]
I think your site wide replacement of `wincent.com` with `wincent.dev` worked little too good. 
The link `https://github.com/wincent/command-t` is replaced with `https://github.com/wincent.devmand-t`, something you might want to fix?

Example : https://wincent.dev/blog/command-t-lua-rewrite

I am not sure if this is the right place to report this.

**Comment by wincent** [comment]
Thanks. I tried to be somewhat careful/surgical about this, but obviously failed! Will fix the instances that I can!
