### ISSUE TITLE
Tagged pages should show up in tag search

### ISSUE THREAD

**Issue by wincent** [wincent/masochist#23]
At the moment I can tag a page like `/pages/about` and it won't show up in the tag search, but it should.

**Comment by rojobuffalo** [comment]
Do you have a hint where this could be fixed? I'm happy to have a crack at it.

**Comment by wincent** [comment]
I would have to look to be sure, but we'll need one or both of these:

(1) Update [the indexer](https://github.com/wincent/masochist/blob/master/app/src/bin/updateIndices.js) to read tags from pages (it is obviously already doing it for wiki articles, blog posts etc).
(2) Update the view code to actually show pages in tag search.

The latter should be pretty easy (if it's necessary at all), but (1) will be pretty gnarly. The indexing code is definitely the scariest part of the code base. I'll look into it a bit more to get a sense of just how much is missing.
