### ISSUE TITLE
When tag count drops to zero, should remove or suppress

### ISSUE THREAD

**Issue by wincent** [wincent/masochist#37]
I just changed a couple of "memcache" tags to "memcached", causing the count for "memcache" to drop to zero.

It is, however, still showing up in the index at https://wincent.com/tags

Worse still, the articles show up at: https://wincent.com/tags/memcache

On the bright side, when you navigate to the actual articles, they do at least show the "memcached" tag and not "memcache".

**Comment by rojobuffalo** [comment]
@wincent I copied this repo and cleared out all but a few content examples. The `/tags` page still shows all the tags with a count of 0. It looks like wincent.com has that same behavior. 

Were you thinking of a way to prevent rendering tags with 0 count? Or is there a "hard reset" path for getting these tags out of the way?

**Comment by wincent** [comment]
I'm on my phone right now so can't confirm the actual details, but from memory you should be able to rebuild the Redis indices to get correct tag counts.

The update script is: https://github.com/wincent/masochist/blob/master/app/src/bin/updateIndices.js 

The cache key for memcached is in: https://github.com/wincent/masochist/blob/master/app/src/common/Cache.js

The cache key for Redis is in: https://github.com/wincent/masochist/blob/master/shared/common.json

But yes, something should be done to make renaming tags easier without having to manually regen indices.

**Comment by rojobuffalo** [comment]
Thanks for the quick response. I flushed both caches and ran the update script, but I'm still seeing the zeros. Is it possible that the git history is affecting things? I was thinking about squashing the git history so those tags never exist.

**Comment by rojobuffalo** [comment]
As mentioned in your notes, bumping the version numbers to manually invalidate the cache is what works. Thanks

**Comment by wincent** [comment]
Thanks for reporting back in. I'll make a separate issue for improving the ergonomics for this use case.
