### ISSUE TITLE
Add RSS support

### ISSUE THREAD

**Issue by elliot42** [wincent/masochist#67]
Your adoring readers want to know if/when a new post is available, without manually polling.  Twitter's not a reliable/conducive way to get this information, so the most reliable standards AFAIK are (still) email mailing list, or RSS.  There's no obvious RSS link present, so this ticket proposes adding RSS support and/or a link when time permits...

**Comment by wincent** [comment]
Funnily enough, I used to have pervasive Atom feeds all over the place in my old Rails website until I [ripped them out](https://github.com/wincent/wincent-on-rails/commit/fbf5996605993847c0e2211d2d4b947b089075e2) when they were getting in the way of the Rails 4 upgrade.

Agreed with you about Twitter probably not being reliable enough, and I am pretty sure feeds can be added in a way that future Rails upgrades (ha!) won't break, so thanks for the suggestion!

**Comment by wincent** [comment]
Not a feed user myself, but I added this in Digg Reader and Feedly to see if it looked ok (it does). @elliot42, let me know if you see anything fishy with it.

**Comment by elliot42** [comment]
Works great, thank you!
