### ISSUE TITLE
404 error - https://wincent.com/a/products/synergy-classic/buttons

### ISSUE THREAD

**Issue by ASGrant55** [wincent/masochist#83]
I can't find the page containing the button library. Please update the link.

**Comment by wincent** [comment]
They are at:

https://www.wincent.com/a/products/synergy-classic/buttons/

Can you please let me know where you found the broken link so that I can update it?

**Comment by ASGrant55** [comment]
The broken link is from the “More” button next to “Menu Style” in the preferences pane, under “Menu Bar”.

This is the link: https://wincent.com/a/products/synergy-classic/buttons

Without “www”, you get a 404 error.

Adam Grant

–


On Feb 2, 2017, at 11:57 AM, Greg Hurrell <notifications@github.com> wrote:

They are at:

https://www.wincent.com/a/products/synergy-classic/buttons/ <https://www.wincent.com/a/products/synergy-classic/buttons/>
Can you please let me know where you found the broken link so that I can update it?
