### ISSUE TITLE
"ost" prefix on page titles in search results

### ISSUE THREAD

**Issue by rojobuffalo** [wincent/masochist#85]
When a "page" type shows up in search results, the title text has "ost" at the front.

Seen here: https://wincent.com/search/presence%20on%20the%20web

**Comment by wincent** [comment]
Bizarre! Thanks for reporting.

[Here it is](https://github.com/wincent/masochist/blob/06c7c9bc26e7cbc05fb33894d6842477f101c07d/app/src/client/components/PagePreview.js#L17). No idea how it got there. Will remove.
